- .github/workflows/release-image.yml
- .github/workflows/test-build.yml
- Makefile
- README.md
- Add kubebuilder make target to install kubebuilder tools. This is required for running envtest.
- Add workflow to run tests and image builds on every push and PR. A `develop` image will be published after every merge.
- Add workflow to publishing release images for "v" prefixed tags.
> Add workflows for test, build and publish

- .github/workflows/develop-image.yml
- .github/workflows/test-build.yml
Must be `on.push.branches`
Refer: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
This was causing the workflow to be triggered for all the branches.
Also,  add timeout for golangci-lint to avoid first run on a new branch failure.
> Fix develop image workflow typo

- go.mod
- internal/controllers/sharedvolume/README.md
- internal/controllers/sharedvolume/controller.go
- internal/controllers/sharedvolume/controller_test.go
- internal/controllers/sharedvolume_e2e_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/shared_volume.go
- internal/pkg/storageos/shared_volume_types.go
The RWX Service should be named afater the PV, not the PVC that created it.  The PV name is unique across the cluster, and allocated immediately before the Service is created.  The PVC name is not suitable as it is common for applications to name the PVC the same as the application Service.
> Use PV name as service name

- .github/workflows/redhat-image.yml
- .github/workflows/release-image.yml
- Add steps to "Publish release image" workflow publish-image job to
tag and push the release image to redhat container registry.
- Add new workflow to manually trigger an image build, based on a
branch, tag or SHA, tag the image and push to redhat container registry.
> Add workflows to publish to redhat container registry

- Dockerfile
Add license and labels required for redhat container image
certification.
https://github.com/storageos/images/tree/master/api-manager
will no longer be used since we are using github actions instead
of redhat build service.
> Dockerfile: Add license and labels

- .github/workflows/test-build.yml
Pipelines were failing due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This fixes them.
> Bump golangci-lint-action

- Dockerfile
- README.md
- config/rbac/role.yaml
- controllers/node-delete/README.md
- controllers/node-delete/controller.go
- controllers/node-delete/controller_test.go
- controllers/node_delete_test.go
- controllers/suite_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/node.go
- main.go
Adds a controller to watch for Kubernetes Node delete events, and to remove the node from the StorageOS cluster if safe.
> Add node delete controller

- README.md
- controllers/namespace-delete/README.md
- controllers/namespace-delete/controller.go
- controllers/namespace_delete_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/namespace.go
- internal/pkg/storageos/shared_volume.go
- main.go
Adds a controller to watch for Kubernetes Namespace delete events, and to remove the namespace from the StorageOS cluster if it doesn't have volumes.
> Add namespace delete controller

- Dockerfile
- Makefile
Change build and tests to use the vendored dependencies.
Also removes the code in the Dockerfile to selectively copy source files since it was intended to speed up the build by not copying in vendored deps (which we now want to do).
> Build and tests should use vendored deps

- .github/workflows/test-build.yml
Ensures changes from `go mod tidy` and `go mod vendor` have been commited.
Failure when dependency missing from vendor: https://github.com/storageos/api-manager/runs/1662859506?check_suite_focus=true
> Add action to ensure modules tidy & vendored

- README.md
- controllers/namespace-delete/README.md
- controllers/namespace-delete/controller.go
- controllers/namespace-delete/predicate.go
- controllers/namespace-delete/reconciler.go
- controllers/namespace_delete_test.go
- controllers/node-delete/README.md
- controllers/node-delete/controller.go
- controllers/node_delete_test.go
- internal/pkg/annotation/csi_driver.go
- internal/pkg/annotation/csi_driver_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/mocks/mock_namespace_deleter.go
- internal/pkg/storageos/namespace.go
- main.go
Updates the namespace delete controller to use the operator toolkit, and adds garbage collection every 1h by default.
> Migrate namespace delete to operator toolkit

- README.md
- main.go
Sets timestamps to use RFC3339Nano format, and adds command-line flags to configure log level and format.
Currently the `-zap-stacktrace-level` is hardcoded to `panic` to avoid stacktraces in the logs for errors that we recover from.  https://github.com/kubernetes-sigs/controller-runtime/pull/1348 addresses this.
Previous log entry:
```
{"level":"info","ts":1611140462.7687058,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
```
New default:
```
{"level":"info","timestamp":"2021-01-20T15:47:44.042084444Z,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
```
> RFC3339Nano timestamps and flags to configure level & format

- controllers/namespace-delete/controller.go
- controllers/node-delete/controller.go
- internal/controllers/sharedvolume/controller.go
- internal/controllers/sharedvolume/controller_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/mocks/mock_namespace_deleter.go
- internal/pkg/storageos/mocks/mock_node_deleter.go
- internal/pkg/storageos/mocks/mock_volume_sharer.go
- internal/pkg/storageos/namespace.go
- internal/pkg/storageos/node.go
- internal/pkg/storageos/shared_volume.go
*Review after https://github.com/storageos/api-manager/pull/22 merges, or only review last commit*
This updates the remaining API function signatures to accept a context, add the auth token and pass to the API client, allowing the caller to set a timeout or cancel the context.
> Pass context to api consistently

- README.md
- controllers/namespace-delete/README.md
- controllers/namespace-delete/reconciler.go
- controllers/namespace_delete_test.go
- controllers/node-delete/README.md
- controllers/node-delete/reconciler.go
- controllers/node-label/README.md
- controllers/node-label/controller.go
- controllers/node-label/reconciler.go
- controllers/node_delete_test.go
- controllers/node_label_sync_test.go
- controllers/pvc-label/README.md
- controllers/pvc-label/controller.go
- controllers/pvc-label/reconciler.go
- controllers/pvc_label_sync_test.go
- controllers/suite_test.go
- go.mod
- go.sum
- main.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/external-object-sync/v1/controller.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/external-object-sync/v1/sync.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/metadata-sync/v1/controller.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/metadata-sync/v1/sync.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/sync/v1/controller.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/sync/v1/sync.go
- vendor/github.com/darkowlzz/operator-toolkit/controller/sync/v1/syncfunc.go
- vendor/modules.txt
Adds flags to configure how long each controller should wait before doing a full resync/garbage collection.  These are set low by default so that they run almost immediately.
> Run resync on startup after a configurable delay

- controllers/namespace-delete/controller.go
- controllers/node-delete/controller.go
- controllers/node-label/controller.go
- controllers/pvc-label/controller.go
- go.mod
- go.sum
- internal/pkg/storageos/client.go
- internal/pkg/storageos/error_format.go
- internal/pkg/storageos/namespace.go
- internal/pkg/storageos/node.go
- internal/pkg/storageos/node_labels.go
- internal/pkg/storageos/shared_volume.go
- internal/pkg/storageos/volume.go
- internal/pkg/storageos/volume_labels.go
- main.go
- vendor/github.com/storageos/go-api/v2/Makefile
- vendor/github.com/storageos/go-api/v2/api/errors.go
- vendor/github.com/storageos/go-api/v2/api/openapi.yaml
- vendor/github.com/storageos/go-api/v2/go.mod
- vendor/github.com/storageos/go-api/v2/map_error.go
- vendor/github.com/storageos/go-api/v2/model_volume.go
- vendor/modules.txt
Maps StorageOS API errors using the same code as the CLI.  This allows us to get full details of the cause of the error in the logs. 
The error mapping code was added to go-api (separate PR coming)
Adds a new formatter for multierror that works better with json output (no tabs or new lines).
Unwraps some errors prior to returning to avoid stack traces getting written when they're logged by the caller.
> Log api reason

- internal/pkg/storageos/node_labels.go
- internal/pkg/storageos/node_labels_test.go
- internal/pkg/storageos/volume_labels_test.go
Similar to volumes, the control plane API expects the current reserved labels to be included in the map of labels sent during a node update, and they must have the same value as there are separate API endpoints to update them.
> Include reserved labels in node label update

- controllers/namespace-delete/controller.go
- controllers/namespace_delete_test.go
- controllers/node-delete/controller.go
- controllers/node-label/controller.go
- controllers/node-label/mocks/mock_node_labeller.go
- controllers/node-label/reconciler.go
- controllers/node_delete_test.go
- controllers/node_label_sync_test.go
- controllers/pvc_label_sync_test.go
- internal/pkg/storageos/mock_client.go
- internal/pkg/storageos/mocks/mock_namespace_deleter.go
- internal/pkg/storageos/mocks/mock_node_deleter.go
- internal/pkg/storageos/namespace.go
- internal/pkg/storageos/node.go
- internal/pkg/storageos/node_labels.go
- internal/pkg/storageos/node_labels_test.go
- internal/pkg/storageos/shared_volume.go
- internal/pkg/storageos/volume.go
- internal/pkg/storageos/volume_labels.go
- internal/pkg/storageos/volume_labels_test.go
No functional changes - this applies the same function signature that was used for Volume API calls to nodes and namespaces, and consolidates some similar functions.
The shared volume `SetExternalEndpoint()` was left as-is as the volume ID is known and used instead as an optimisation.
> Standardise on ObjectKeys for all API function signatures

- controllers/namespace_delete_test.go
- controllers/node_delete_test.go
- controllers/node_label_sync_test.go
- controllers/pvc_label_sync_test.go
- internal/controllers/sharedvolume/controller.go
- internal/controllers/sharedvolume/controller_test.go
- internal/controllers/suite_test.go
- internal/pkg/storageos/client.go
- main.go
Code simplification to let controller manager handle startup and shutdown of non-k8s controllers like the SharedVolume controller.
> Run shared volume controller with manager

- .dockerignore
- .github/workflows/test-build.yml
- .gitignore
- Makefile
- PROJECT
- config/manager/kustomization.yaml
- config/webhook/manifests.yaml
- controllers/admission/scheduler/handler.go
- Updates the makefile to be based on the kubebuilder v3 makefile.
- Update kubebuilder, controller-tools and kustomize dependencies. All
the binaries are downloaded into ./bin dir. And all the test related
binaries are downloaded in testbin. Old assets in
/usr/local/kubebuilder/ can be deleted. All the dependencies are
maintained within the project directory.
- envtest related tools are downloaded when the tests are run. All build
and test dependencies are self-contained now.
- Update all the generated code and configs.
- make help shows a list of all the targets with description.
NOTE: We have already been using most of the kubebuilder v3 dependencies
with the latest stable controller-runtime. This change moves the project scaffold,
code generation and testing tools to the versions used …
> Migrate to kubebuilder v3

- README.md
- config/webhook/manifests.yaml
- controllers/pod-mutator/README.md
- controllers/pvc-mutator/README.md
- controllers/pvc-mutator/controller.go
- controllers/pvc_mutator_test.go
- controllers/test_helpers.go
- main.go
Adds the controller to handle mutating PVC create requests.  There will be a separate operator PR to create the MutatingWebhookConfiguration, but this can come later.
No mutators have been added at this point.
I'll re-target to master after https://github.com/storageos/api-manager/pull/41 merges.
> Add PVC mutating controller

- README.md
- controllers/node-label/README.md
- controllers/pvc-label/README.md
- main.go
Adds command-line flags to disable the node and pvc label sync controllers completely.  They remain enabled by default.
> Add flags to disable label sync controllers

- Makefile
- controllers/pvc-label/README.md
- controllers/pvc-label/controller.go
- controllers/pvc-label/reconciler.go
- controllers/pvc-mutator/README.md
- controllers/pvc-mutator/storageclass/README.md
- controllers/pvc-mutator/storageclass/annotation.go
- controllers/pvc-mutator/storageclass/annotation_test.go
- controllers/pvc_keygen_test.go
- controllers/pvc_label_sync_test.go
- controllers/pvc_storageclass_test.go
- controllers/scheduler_test.go
- controllers/suite_test.go
- internal/pkg/provisioner/storageclass.go
- internal/pkg/provisioner/storageos.go
- internal/pkg/provisioner/storageos_test.go
- main.go
Prior to applying labels after a change has been detected, defaults are loaded from the StorageClass parameters that provisioned the volume.  This ensures that the defaults set in the StorageClass are not overwritten because there is not a corresponding label on the PVC.
Since StorageClasses are immutable the params can't be changed after the volume has been provisioned.  To protect against the SC being deleted and re-added with different params, a reference to the original SC's UID is stored in an annotation on the PVC.  If the current SC does not match, an error is logged and label sync is disabled for that PVC.
> Add defaults from StorageClass

- internal/pkg/storageos/mock_client.go
Fixes an e2e test flake where if the randomly generated endpoint IP address is a loopback address then the Kubernetes API will reject it.  Validation function: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L5769-L5789
Test failure https://github.com/storageos/api-manager/pull/55/checks?check_run_id=2422375036:
```
failed to create endpoints resource: Endpoints \"pvc-d6941232-6432-43bf-b5de-59c999641a09\" is invalid: subsets[0].addresses[0].ip: Invalid value: \"127.136.127.136\": may not be in the loopback range (127.0.0.0/8)"
```
The crude fix is to ensure the first octet is between 1-101.
> Test flake: Random endpoint ip address should not be a loopback address

- controllers/pod_mutator_test.go
- controllers/pvc-mutator/encryption/keygen.go
- controllers/pvc_keygen_test.go
- controllers/pvc_mutator_test.go
- controllers/pvc_storageclass_test.go
- controllers/scheduler_test.go
- go.mod
- go.sum
- main.go
- vendor/github.com/darkowlzz/operator-toolkit/client/composite/client.go
- vendor/github.com/darkowlzz/operator-toolkit/client/composite/doc.go
- vendor/modules.txt
This change replaces all the cached/uncached clients in admission
controllers with a composite client. The composite client will help
handle the cases where the cached client can't find the recently
created resources. The composite client will retry the query using
the raw client to query the k8s API server directly.
Refer https://pkg.go.dev/github.com/darkowlzz/operator-toolkit@v0.0.0-20210423182126-723c7a1e8b45/client/composite for details about the composite client.
> Use composite client in admission controllers

- controllers/pvc_storageclass_test.go
Previously the test compared the entire PVC with itself on case of "changes not needed" which doesn't make much sense and because there was a misconfiguration in test cases this was hidden. I fixed the config and decrease the scope of comparison.
> Fix storageclass annotation int. tests

- controllers/pvc_keygen_test.go
"the pre-create PVC won't have metadata like the PVC UID so a compare of the whole object will always fail. It passed before as I missed that because I was passing in pvc as a reference, the create call was updating it with the post-create object. The test always passes." Thanks @croomes
> Verify annotations in keygen test

- controllers/pvc-mutator/encryption/keygen.go
- controllers/pvc-mutator/encryption/keygen_test.go
- controllers/pvc_keygen_test.go
Original version checked encryption label only at the PVC, but encryption should be inherited from storage class. This change adds this ability.
The original encryption label parser forced un-encrypted storage creation if the label was invalid. This behavior leads to non encrypted volumes if user made a typo in label, which is not the safest way to handle the case. After this change invalid label value will block the PVC creation.
> Check encryption flag in storage class

- controllers/pvc-label/controller.go
- controllers/pvc_label_sync_test.go
- internal/pkg/provisioner/storageclass.go
Currently if label sync finds the UID annotation it compares it to the current version of the StorageClass.
If it doesn't match, stop syncing the labels and some user action is needed.
If it isn't found it fetches the StorageClass and passes the parameters as labels.
In some edge cases we have the risk that we synchronize wrong parameters, because the parameters were different in the time of the PVC creation.
This change introduces usage of creation time to more safely use the underlying StorageClass, if SC is older, use it, if younger just stop syncing and ask the user to do some action.
> Compare SC and PVC creation time during label sync

- config/rbac/leader_election_role.yaml
Adding to rbac config - normally added by kubebuilder (fixed in 3.0.0)
> Leader election requires ability to patch events
